/********************************************************************************
** Form generated from reading UI file 'stats.ui'
**
** Created: Wed 23. Mar 21:32:51 2011
**      by: Qt User Interface Compiler version 4.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_STATS_H
#define UI_STATS_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QToolBox>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionAbout;
    QAction *actionExit;
    QAction *actionDataClipboard;
    QAction *actionRefreshData;
    QAction *actionCheck_for_update;
    QAction *actionSettings;
    QAction *actionDonate;
    QWidget *centralWidget;
    QToolBox *toolBox;
    QWidget *page;
    QGroupBox *groupBox;
    QLabel *label;
    QLabel *label_4;
    QLabel *label_3;
    QLabel *label_2;
    QLabel *label_5;
    QLineEdit *pong2Edit;
    QLineEdit *bibleQuizEdit;
    QLineEdit *redSquareEdit;
    QLineEdit *spaceBubbleEdit;
    QLineEdit *towerDefenseEdit;
    QLineEdit *KnightsQuestEdit;
    QLabel *label_30;
    QGroupBox *groupBox_2;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLineEdit *pong2Edit3;
    QLineEdit *bibleQuizEdit3;
    QLineEdit *redSquareEdit3;
    QLineEdit *spaceBubbleEdit3;
    QLineEdit *towerDefenseEdit3;
    QLineEdit *KnightsQuestEdit3;
    QLabel *label_32;
    QGroupBox *groupBox_4;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *pong2Edit4;
    QLineEdit *bibleQuizEdit4;
    QLineEdit *redSquareEdit4;
    QLineEdit *spaceBubbleEdit4;
    QLineEdit *towerDefenseEdit4;
    QLineEdit *KnightsQuestEdit4;
    QLabel *label_33;
    QGroupBox *groupBox_5;
    QLineEdit *totals;
    QLineEdit *totals2;
    QLineEdit *totals3;
    QLineEdit *totals4;
    QGroupBox *groupBox_3;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLineEdit *pong2Edit2;
    QLineEdit *bibleQuizEdit2;
    QLineEdit *redSquareEdit2;
    QLineEdit *spaceBubbleEdit2;
    QLineEdit *towerDefenseEdit2;
    QLineEdit *KnightsQuestEdit2;
    QLabel *label_31;
    QWidget *page_2;
    QGroupBox *groupBox_6;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLineEdit *addressbookEdit1;
    QLineEdit *eventNotificationEdit1;
    QLineEdit *churchEdit1;
    QGroupBox *groupBox_7;
    QLineEdit *totalsDrupalEdit1;
    QLineEdit *totalsDrupalEdit2;
    QLineEdit *totalsDrupalEdit3;
    QGroupBox *groupBox_8;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLineEdit *addressbookEdit2;
    QLineEdit *eventNotificationEdit2;
    QLineEdit *churchEdit2;
    QGroupBox *groupBox_9;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLineEdit *addressbookEdit3;
    QLineEdit *eventNotificationEdit3;
    QLineEdit *churchEdit3;
    QWidget *page_3;
    QGroupBox *groupBox_10;
    QLineEdit *totalsWindowsEdit1;
    QLineEdit *totalsWindowsEdit2;
    QLineEdit *totalsWindowsEdit3;
    QGroupBox *groupBox_11;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLineEdit *plaatstatsEdit2;
    QLineEdit *plaatscoreEdit2;
    QLineEdit *winredsquareEdit2;
    QLineEdit *winKnightsQuestEdit2;
    QLabel *label_48;
    QLineEdit *winChatCostCalcEdit2;
    QLabel *label_51;
    QLineEdit *winWarQuestClientEdit2;
    QLabel *label_54;
    QGroupBox *groupBox_12;
    QLabel *label_38;
    QLabel *label_40;
    QLineEdit *plaatstatsEdit1;
    QLineEdit *plaatscoreEdit1;
    QLineEdit *winredsquareEdit1;
    QLabel *label_46;
    QLabel *label_47;
    QLineEdit *winKnightsQuestEdit1;
    QLineEdit *winChatCostCalcEdit1;
    QLabel *label_50;
    QLabel *label_53;
    QLineEdit *winWarQuestClientEdit1;
    QGroupBox *groupBox_13;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLineEdit *plaatstatsEdit3;
    QLineEdit *plaatscoreEdit3;
    QLineEdit *winredsquareEdit3;
    QLabel *label_49;
    QLineEdit *winKnightsQuestEdit3;
    QLineEdit *winChatCostCalcEdit3;
    QLabel *label_52;
    QLineEdit *winWarQuestClientEdit3;
    QLabel *label_55;
    QMenuBar *menuBar;
    QMenu *menuExit;
    QMenu *menuHelp;
    QMenu *menuEdit;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(368, 503);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        QIcon icon;
        icon.addFile(QString::fromUtf8("images/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionDataClipboard = new QAction(MainWindow);
        actionDataClipboard->setObjectName(QString::fromUtf8("actionDataClipboard"));
        actionRefreshData = new QAction(MainWindow);
        actionRefreshData->setObjectName(QString::fromUtf8("actionRefreshData"));
        actionCheck_for_update = new QAction(MainWindow);
        actionCheck_for_update->setObjectName(QString::fromUtf8("actionCheck_for_update"));
        actionSettings = new QAction(MainWindow);
        actionSettings->setObjectName(QString::fromUtf8("actionSettings"));
        actionDonate = new QAction(MainWindow);
        actionDonate->setObjectName(QString::fromUtf8("actionDonate"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        toolBox = new QToolBox(centralWidget);
        toolBox->setObjectName(QString::fromUtf8("toolBox"));
        toolBox->setGeometry(QRect(10, 10, 351, 461));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        page->setGeometry(QRect(0, 0, 351, 380));
        groupBox = new QGroupBox(page);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(0, 0, 81, 321));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 20, 69, 13));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 120, 69, 13));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 70, 69, 13));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 170, 69, 13));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 220, 69, 13));
        pong2Edit = new QLineEdit(groupBox);
        pong2Edit->setObjectName(QString::fromUtf8("pong2Edit"));
        pong2Edit->setGeometry(QRect(10, 40, 61, 20));
        pong2Edit->setReadOnly(true);
        bibleQuizEdit = new QLineEdit(groupBox);
        bibleQuizEdit->setObjectName(QString::fromUtf8("bibleQuizEdit"));
        bibleQuizEdit->setGeometry(QRect(10, 90, 61, 20));
        bibleQuizEdit->setReadOnly(true);
        redSquareEdit = new QLineEdit(groupBox);
        redSquareEdit->setObjectName(QString::fromUtf8("redSquareEdit"));
        redSquareEdit->setGeometry(QRect(10, 140, 61, 20));
        redSquareEdit->setReadOnly(true);
        spaceBubbleEdit = new QLineEdit(groupBox);
        spaceBubbleEdit->setObjectName(QString::fromUtf8("spaceBubbleEdit"));
        spaceBubbleEdit->setGeometry(QRect(10, 190, 61, 20));
        spaceBubbleEdit->setReadOnly(true);
        towerDefenseEdit = new QLineEdit(groupBox);
        towerDefenseEdit->setObjectName(QString::fromUtf8("towerDefenseEdit"));
        towerDefenseEdit->setGeometry(QRect(10, 240, 61, 20));
        towerDefenseEdit->setReadOnly(true);
        KnightsQuestEdit = new QLineEdit(groupBox);
        KnightsQuestEdit->setObjectName(QString::fromUtf8("KnightsQuestEdit"));
        KnightsQuestEdit->setGeometry(QRect(10, 290, 61, 20));
        KnightsQuestEdit->setReadOnly(true);
        label_30 = new QLabel(groupBox);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 270, 69, 13));
        groupBox_2 = new QGroupBox(page);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(180, 0, 81, 321));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 20, 101, 16));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 70, 101, 16));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 120, 91, 16));
        label_14 = new QLabel(groupBox_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 170, 91, 16));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 220, 81, 16));
        pong2Edit3 = new QLineEdit(groupBox_2);
        pong2Edit3->setObjectName(QString::fromUtf8("pong2Edit3"));
        pong2Edit3->setGeometry(QRect(10, 40, 61, 20));
        pong2Edit3->setReadOnly(true);
        bibleQuizEdit3 = new QLineEdit(groupBox_2);
        bibleQuizEdit3->setObjectName(QString::fromUtf8("bibleQuizEdit3"));
        bibleQuizEdit3->setGeometry(QRect(10, 90, 61, 20));
        bibleQuizEdit3->setReadOnly(true);
        redSquareEdit3 = new QLineEdit(groupBox_2);
        redSquareEdit3->setObjectName(QString::fromUtf8("redSquareEdit3"));
        redSquareEdit3->setGeometry(QRect(10, 140, 61, 20));
        redSquareEdit3->setReadOnly(true);
        spaceBubbleEdit3 = new QLineEdit(groupBox_2);
        spaceBubbleEdit3->setObjectName(QString::fromUtf8("spaceBubbleEdit3"));
        spaceBubbleEdit3->setGeometry(QRect(10, 190, 61, 20));
        spaceBubbleEdit3->setReadOnly(true);
        towerDefenseEdit3 = new QLineEdit(groupBox_2);
        towerDefenseEdit3->setObjectName(QString::fromUtf8("towerDefenseEdit3"));
        towerDefenseEdit3->setGeometry(QRect(10, 240, 61, 20));
        towerDefenseEdit3->setReadOnly(true);
        KnightsQuestEdit3 = new QLineEdit(groupBox_2);
        KnightsQuestEdit3->setObjectName(QString::fromUtf8("KnightsQuestEdit3"));
        KnightsQuestEdit3->setGeometry(QRect(10, 290, 61, 20));
        KnightsQuestEdit3->setReadOnly(true);
        label_32 = new QLabel(groupBox_2);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 270, 81, 16));
        groupBox_4 = new QGroupBox(page);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(270, 0, 81, 321));
        label_16 = new QLabel(groupBox_4);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 20, 71, 16));
        label_17 = new QLabel(groupBox_4);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 70, 71, 16));
        label_18 = new QLabel(groupBox_4);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 120, 71, 16));
        label_19 = new QLabel(groupBox_4);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 170, 71, 16));
        label_20 = new QLabel(groupBox_4);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 220, 71, 16));
        pong2Edit4 = new QLineEdit(groupBox_4);
        pong2Edit4->setObjectName(QString::fromUtf8("pong2Edit4"));
        pong2Edit4->setGeometry(QRect(10, 40, 61, 20));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        pong2Edit4->setFont(font);
        pong2Edit4->setReadOnly(true);
        bibleQuizEdit4 = new QLineEdit(groupBox_4);
        bibleQuizEdit4->setObjectName(QString::fromUtf8("bibleQuizEdit4"));
        bibleQuizEdit4->setGeometry(QRect(10, 90, 61, 20));
        bibleQuizEdit4->setFont(font);
        bibleQuizEdit4->setReadOnly(true);
        redSquareEdit4 = new QLineEdit(groupBox_4);
        redSquareEdit4->setObjectName(QString::fromUtf8("redSquareEdit4"));
        redSquareEdit4->setGeometry(QRect(10, 140, 61, 20));
        redSquareEdit4->setFont(font);
        redSquareEdit4->setReadOnly(true);
        spaceBubbleEdit4 = new QLineEdit(groupBox_4);
        spaceBubbleEdit4->setObjectName(QString::fromUtf8("spaceBubbleEdit4"));
        spaceBubbleEdit4->setGeometry(QRect(10, 190, 61, 20));
        spaceBubbleEdit4->setFont(font);
        spaceBubbleEdit4->setReadOnly(true);
        towerDefenseEdit4 = new QLineEdit(groupBox_4);
        towerDefenseEdit4->setObjectName(QString::fromUtf8("towerDefenseEdit4"));
        towerDefenseEdit4->setGeometry(QRect(10, 240, 61, 20));
        towerDefenseEdit4->setFont(font);
        towerDefenseEdit4->setReadOnly(true);
        KnightsQuestEdit4 = new QLineEdit(groupBox_4);
        KnightsQuestEdit4->setObjectName(QString::fromUtf8("KnightsQuestEdit4"));
        KnightsQuestEdit4->setGeometry(QRect(10, 290, 61, 20));
        KnightsQuestEdit4->setFont(font);
        KnightsQuestEdit4->setReadOnly(true);
        label_33 = new QLabel(groupBox_4);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(10, 270, 71, 16));
        groupBox_5 = new QGroupBox(page);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(0, 330, 351, 49));
        totals = new QLineEdit(groupBox_5);
        totals->setObjectName(QString::fromUtf8("totals"));
        totals->setGeometry(QRect(10, 20, 61, 20));
        totals->setFont(font);
        totals->setReadOnly(true);
        totals2 = new QLineEdit(groupBox_5);
        totals2->setObjectName(QString::fromUtf8("totals2"));
        totals2->setGeometry(QRect(100, 20, 61, 20));
        totals2->setFont(font);
        totals2->setReadOnly(true);
        totals3 = new QLineEdit(groupBox_5);
        totals3->setObjectName(QString::fromUtf8("totals3"));
        totals3->setGeometry(QRect(190, 20, 61, 20));
        totals3->setFont(font);
        totals3->setReadOnly(true);
        totals4 = new QLineEdit(groupBox_5);
        totals4->setObjectName(QString::fromUtf8("totals4"));
        totals4->setGeometry(QRect(280, 20, 61, 20));
        totals4->setFont(font);
        totals4->setReadOnly(true);
        groupBox_3 = new QGroupBox(page);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(90, 0, 81, 321));
        label_6 = new QLabel(groupBox_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 20, 79, 13));
        label_7 = new QLabel(groupBox_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 70, 79, 13));
        label_8 = new QLabel(groupBox_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 120, 79, 13));
        label_9 = new QLabel(groupBox_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 170, 79, 13));
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 220, 79, 13));
        pong2Edit2 = new QLineEdit(groupBox_3);
        pong2Edit2->setObjectName(QString::fromUtf8("pong2Edit2"));
        pong2Edit2->setGeometry(QRect(10, 40, 61, 20));
        pong2Edit2->setReadOnly(true);
        bibleQuizEdit2 = new QLineEdit(groupBox_3);
        bibleQuizEdit2->setObjectName(QString::fromUtf8("bibleQuizEdit2"));
        bibleQuizEdit2->setGeometry(QRect(10, 90, 61, 20));
        bibleQuizEdit2->setReadOnly(true);
        redSquareEdit2 = new QLineEdit(groupBox_3);
        redSquareEdit2->setObjectName(QString::fromUtf8("redSquareEdit2"));
        redSquareEdit2->setGeometry(QRect(10, 140, 61, 20));
        redSquareEdit2->setReadOnly(true);
        spaceBubbleEdit2 = new QLineEdit(groupBox_3);
        spaceBubbleEdit2->setObjectName(QString::fromUtf8("spaceBubbleEdit2"));
        spaceBubbleEdit2->setGeometry(QRect(10, 190, 61, 20));
        spaceBubbleEdit2->setReadOnly(true);
        towerDefenseEdit2 = new QLineEdit(groupBox_3);
        towerDefenseEdit2->setObjectName(QString::fromUtf8("towerDefenseEdit2"));
        towerDefenseEdit2->setGeometry(QRect(10, 240, 61, 20));
        towerDefenseEdit2->setReadOnly(true);
        KnightsQuestEdit2 = new QLineEdit(groupBox_3);
        KnightsQuestEdit2->setObjectName(QString::fromUtf8("KnightsQuestEdit2"));
        KnightsQuestEdit2->setGeometry(QRect(10, 290, 61, 20));
        KnightsQuestEdit2->setReadOnly(true);
        label_31 = new QLabel(groupBox_3);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 270, 79, 13));
        toolBox->addItem(page, QString::fromUtf8("Wii Downloads"));
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        page_2->setGeometry(QRect(0, 0, 351, 380));
        groupBox_6 = new QGroupBox(page_2);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(0, 0, 110, 311));
        label_21 = new QLabel(groupBox_6);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 20, 79, 13));
        label_22 = new QLabel(groupBox_6);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 70, 101, 16));
        label_23 = new QLabel(groupBox_6);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 120, 111, 16));
        addressbookEdit1 = new QLineEdit(groupBox_6);
        addressbookEdit1->setObjectName(QString::fromUtf8("addressbookEdit1"));
        addressbookEdit1->setGeometry(QRect(10, 40, 91, 20));
        addressbookEdit1->setReadOnly(true);
        eventNotificationEdit1 = new QLineEdit(groupBox_6);
        eventNotificationEdit1->setObjectName(QString::fromUtf8("eventNotificationEdit1"));
        eventNotificationEdit1->setGeometry(QRect(10, 90, 90, 20));
        eventNotificationEdit1->setReadOnly(true);
        churchEdit1 = new QLineEdit(groupBox_6);
        churchEdit1->setObjectName(QString::fromUtf8("churchEdit1"));
        churchEdit1->setGeometry(QRect(10, 140, 88, 20));
        churchEdit1->setReadOnly(true);
        groupBox_7 = new QGroupBox(page_2);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(0, 320, 351, 51));
        totalsDrupalEdit1 = new QLineEdit(groupBox_7);
        totalsDrupalEdit1->setObjectName(QString::fromUtf8("totalsDrupalEdit1"));
        totalsDrupalEdit1->setGeometry(QRect(10, 20, 87, 20));
        totalsDrupalEdit1->setFont(font);
        totalsDrupalEdit1->setReadOnly(true);
        totalsDrupalEdit2 = new QLineEdit(groupBox_7);
        totalsDrupalEdit2->setObjectName(QString::fromUtf8("totalsDrupalEdit2"));
        totalsDrupalEdit2->setGeometry(QRect(130, 20, 87, 20));
        totalsDrupalEdit2->setFont(font);
        totalsDrupalEdit2->setReadOnly(true);
        totalsDrupalEdit3 = new QLineEdit(groupBox_7);
        totalsDrupalEdit3->setObjectName(QString::fromUtf8("totalsDrupalEdit3"));
        totalsDrupalEdit3->setGeometry(QRect(250, 20, 87, 20));
        totalsDrupalEdit3->setFont(font);
        totalsDrupalEdit3->setReadOnly(true);
        groupBox_8 = new QGroupBox(page_2);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(122, -1, 105, 311));
        label_24 = new QLabel(groupBox_8);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 20, 79, 13));
        label_25 = new QLabel(groupBox_8);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 70, 101, 16));
        label_26 = new QLabel(groupBox_8);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(10, 120, 111, 16));
        addressbookEdit2 = new QLineEdit(groupBox_8);
        addressbookEdit2->setObjectName(QString::fromUtf8("addressbookEdit2"));
        addressbookEdit2->setGeometry(QRect(10, 40, 84, 20));
        addressbookEdit2->setReadOnly(true);
        eventNotificationEdit2 = new QLineEdit(groupBox_8);
        eventNotificationEdit2->setObjectName(QString::fromUtf8("eventNotificationEdit2"));
        eventNotificationEdit2->setGeometry(QRect(10, 90, 84, 20));
        eventNotificationEdit2->setReadOnly(true);
        churchEdit2 = new QLineEdit(groupBox_8);
        churchEdit2->setObjectName(QString::fromUtf8("churchEdit2"));
        churchEdit2->setGeometry(QRect(10, 140, 83, 20));
        churchEdit2->setReadOnly(true);
        groupBox_9 = new QGroupBox(page_2);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(238, 0, 111, 311));
        label_27 = new QLabel(groupBox_9);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(10, 20, 79, 13));
        label_28 = new QLabel(groupBox_9);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 70, 101, 16));
        label_29 = new QLabel(groupBox_9);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 120, 111, 16));
        addressbookEdit3 = new QLineEdit(groupBox_9);
        addressbookEdit3->setObjectName(QString::fromUtf8("addressbookEdit3"));
        addressbookEdit3->setGeometry(QRect(10, 40, 84, 20));
        addressbookEdit3->setFont(font);
        addressbookEdit3->setReadOnly(true);
        eventNotificationEdit3 = new QLineEdit(groupBox_9);
        eventNotificationEdit3->setObjectName(QString::fromUtf8("eventNotificationEdit3"));
        eventNotificationEdit3->setGeometry(QRect(10, 90, 84, 20));
        eventNotificationEdit3->setFont(font);
        eventNotificationEdit3->setReadOnly(true);
        churchEdit3 = new QLineEdit(groupBox_9);
        churchEdit3->setObjectName(QString::fromUtf8("churchEdit3"));
        churchEdit3->setGeometry(QRect(10, 140, 83, 20));
        churchEdit3->setFont(font);
        churchEdit3->setReadOnly(true);
        toolBox->addItem(page_2, QString::fromUtf8("Drupal Downloads"));
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        page_3->setGeometry(QRect(0, 0, 351, 380));
        groupBox_10 = new QGroupBox(page_3);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(0, 323, 351, 51));
        totalsWindowsEdit1 = new QLineEdit(groupBox_10);
        totalsWindowsEdit1->setObjectName(QString::fromUtf8("totalsWindowsEdit1"));
        totalsWindowsEdit1->setGeometry(QRect(10, 20, 87, 20));
        totalsWindowsEdit1->setFont(font);
        totalsWindowsEdit1->setReadOnly(true);
        totalsWindowsEdit2 = new QLineEdit(groupBox_10);
        totalsWindowsEdit2->setObjectName(QString::fromUtf8("totalsWindowsEdit2"));
        totalsWindowsEdit2->setGeometry(QRect(130, 20, 87, 20));
        totalsWindowsEdit2->setFont(font);
        totalsWindowsEdit2->setReadOnly(true);
        totalsWindowsEdit3 = new QLineEdit(groupBox_10);
        totalsWindowsEdit3->setObjectName(QString::fromUtf8("totalsWindowsEdit3"));
        totalsWindowsEdit3->setGeometry(QRect(250, 20, 87, 20));
        totalsWindowsEdit3->setFont(font);
        totalsWindowsEdit3->setReadOnly(true);
        groupBox_11 = new QGroupBox(page_3);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(122, 0, 105, 321));
        label_35 = new QLabel(groupBox_11);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 20, 79, 13));
        label_36 = new QLabel(groupBox_11);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(10, 70, 101, 16));
        label_37 = new QLabel(groupBox_11);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(10, 120, 111, 16));
        plaatstatsEdit2 = new QLineEdit(groupBox_11);
        plaatstatsEdit2->setObjectName(QString::fromUtf8("plaatstatsEdit2"));
        plaatstatsEdit2->setGeometry(QRect(10, 40, 84, 20));
        plaatstatsEdit2->setReadOnly(true);
        plaatscoreEdit2 = new QLineEdit(groupBox_11);
        plaatscoreEdit2->setObjectName(QString::fromUtf8("plaatscoreEdit2"));
        plaatscoreEdit2->setGeometry(QRect(10, 90, 84, 20));
        plaatscoreEdit2->setReadOnly(true);
        winredsquareEdit2 = new QLineEdit(groupBox_11);
        winredsquareEdit2->setObjectName(QString::fromUtf8("winredsquareEdit2"));
        winredsquareEdit2->setGeometry(QRect(10, 140, 83, 20));
        winredsquareEdit2->setReadOnly(true);
        winKnightsQuestEdit2 = new QLineEdit(groupBox_11);
        winKnightsQuestEdit2->setObjectName(QString::fromUtf8("winKnightsQuestEdit2"));
        winKnightsQuestEdit2->setGeometry(QRect(10, 190, 81, 20));
        winKnightsQuestEdit2->setReadOnly(true);
        label_48 = new QLabel(groupBox_11);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(10, 170, 81, 16));
        winChatCostCalcEdit2 = new QLineEdit(groupBox_11);
        winChatCostCalcEdit2->setObjectName(QString::fromUtf8("winChatCostCalcEdit2"));
        winChatCostCalcEdit2->setGeometry(QRect(10, 240, 81, 20));
        winChatCostCalcEdit2->setReadOnly(true);
        label_51 = new QLabel(groupBox_11);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 220, 81, 16));
        winWarQuestClientEdit2 = new QLineEdit(groupBox_11);
        winWarQuestClientEdit2->setObjectName(QString::fromUtf8("winWarQuestClientEdit2"));
        winWarQuestClientEdit2->setGeometry(QRect(10, 290, 81, 20));
        winWarQuestClientEdit2->setReadOnly(true);
        label_54 = new QLabel(groupBox_11);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(10, 270, 81, 16));
        groupBox_12 = new QGroupBox(page_3);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(0, 0, 111, 321));
        label_38 = new QLabel(groupBox_12);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(10, 20, 79, 13));
        label_40 = new QLabel(groupBox_12);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 120, 81, 16));
        plaatstatsEdit1 = new QLineEdit(groupBox_12);
        plaatstatsEdit1->setObjectName(QString::fromUtf8("plaatstatsEdit1"));
        plaatstatsEdit1->setGeometry(QRect(10, 40, 91, 20));
        plaatstatsEdit1->setReadOnly(true);
        plaatscoreEdit1 = new QLineEdit(groupBox_12);
        plaatscoreEdit1->setObjectName(QString::fromUtf8("plaatscoreEdit1"));
        plaatscoreEdit1->setGeometry(QRect(10, 90, 90, 20));
        plaatscoreEdit1->setReadOnly(true);
        winredsquareEdit1 = new QLineEdit(groupBox_12);
        winredsquareEdit1->setObjectName(QString::fromUtf8("winredsquareEdit1"));
        winredsquareEdit1->setGeometry(QRect(10, 140, 88, 20));
        winredsquareEdit1->setReadOnly(true);
        label_46 = new QLabel(groupBox_12);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(10, 70, 91, 16));
        label_47 = new QLabel(groupBox_12);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(10, 170, 81, 16));
        winKnightsQuestEdit1 = new QLineEdit(groupBox_12);
        winKnightsQuestEdit1->setObjectName(QString::fromUtf8("winKnightsQuestEdit1"));
        winKnightsQuestEdit1->setGeometry(QRect(10, 190, 88, 20));
        winKnightsQuestEdit1->setReadOnly(true);
        winChatCostCalcEdit1 = new QLineEdit(groupBox_12);
        winChatCostCalcEdit1->setObjectName(QString::fromUtf8("winChatCostCalcEdit1"));
        winChatCostCalcEdit1->setGeometry(QRect(10, 240, 88, 20));
        winChatCostCalcEdit1->setReadOnly(true);
        label_50 = new QLabel(groupBox_12);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(10, 220, 81, 16));
        label_53 = new QLabel(groupBox_12);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(10, 270, 81, 16));
        winWarQuestClientEdit1 = new QLineEdit(groupBox_12);
        winWarQuestClientEdit1->setObjectName(QString::fromUtf8("winWarQuestClientEdit1"));
        winWarQuestClientEdit1->setGeometry(QRect(10, 290, 88, 20));
        winWarQuestClientEdit1->setReadOnly(true);
        groupBox_13 = new QGroupBox(page_3);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(240, 0, 111, 321));
        label_43 = new QLabel(groupBox_13);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(10, 20, 79, 13));
        label_44 = new QLabel(groupBox_13);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 70, 101, 16));
        label_45 = new QLabel(groupBox_13);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(10, 120, 111, 16));
        plaatstatsEdit3 = new QLineEdit(groupBox_13);
        plaatstatsEdit3->setObjectName(QString::fromUtf8("plaatstatsEdit3"));
        plaatstatsEdit3->setGeometry(QRect(10, 40, 81, 20));
        plaatstatsEdit3->setFont(font);
        plaatstatsEdit3->setReadOnly(true);
        plaatscoreEdit3 = new QLineEdit(groupBox_13);
        plaatscoreEdit3->setObjectName(QString::fromUtf8("plaatscoreEdit3"));
        plaatscoreEdit3->setGeometry(QRect(10, 90, 84, 20));
        plaatscoreEdit3->setFont(font);
        plaatscoreEdit3->setReadOnly(true);
        winredsquareEdit3 = new QLineEdit(groupBox_13);
        winredsquareEdit3->setObjectName(QString::fromUtf8("winredsquareEdit3"));
        winredsquareEdit3->setGeometry(QRect(10, 140, 83, 20));
        winredsquareEdit3->setFont(font);
        winredsquareEdit3->setReadOnly(true);
        label_49 = new QLabel(groupBox_13);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(10, 170, 81, 16));
        winKnightsQuestEdit3 = new QLineEdit(groupBox_13);
        winKnightsQuestEdit3->setObjectName(QString::fromUtf8("winKnightsQuestEdit3"));
        winKnightsQuestEdit3->setGeometry(QRect(10, 190, 81, 20));
        winKnightsQuestEdit3->setFont(font);
        winKnightsQuestEdit3->setReadOnly(true);
        winChatCostCalcEdit3 = new QLineEdit(groupBox_13);
        winChatCostCalcEdit3->setObjectName(QString::fromUtf8("winChatCostCalcEdit3"));
        winChatCostCalcEdit3->setGeometry(QRect(10, 240, 81, 20));
        winChatCostCalcEdit3->setFont(font);
        winChatCostCalcEdit3->setReadOnly(true);
        label_52 = new QLabel(groupBox_13);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(10, 220, 81, 16));
        winWarQuestClientEdit3 = new QLineEdit(groupBox_13);
        winWarQuestClientEdit3->setObjectName(QString::fromUtf8("winWarQuestClientEdit3"));
        winWarQuestClientEdit3->setGeometry(QRect(10, 290, 81, 20));
        winWarQuestClientEdit3->setFont(font);
        winWarQuestClientEdit3->setReadOnly(true);
        label_55 = new QLabel(groupBox_13);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 270, 81, 16));
        toolBox->addItem(page_3, QString::fromUtf8("Windows Downloads"));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 368, 20));
        menuExit = new QMenu(menuBar);
        menuExit->setObjectName(QString::fromUtf8("menuExit"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        menuEdit = new QMenu(menuBar);
        menuEdit->setObjectName(QString::fromUtf8("menuEdit"));
        MainWindow->setMenuBar(menuBar);
        QWidget::setTabOrder(pong2Edit, pong2Edit2);
        QWidget::setTabOrder(pong2Edit2, pong2Edit3);
        QWidget::setTabOrder(pong2Edit3, pong2Edit4);
        QWidget::setTabOrder(pong2Edit4, bibleQuizEdit);
        QWidget::setTabOrder(bibleQuizEdit, bibleQuizEdit2);
        QWidget::setTabOrder(bibleQuizEdit2, bibleQuizEdit3);
        QWidget::setTabOrder(bibleQuizEdit3, bibleQuizEdit4);
        QWidget::setTabOrder(bibleQuizEdit4, redSquareEdit);
        QWidget::setTabOrder(redSquareEdit, redSquareEdit2);
        QWidget::setTabOrder(redSquareEdit2, redSquareEdit3);
        QWidget::setTabOrder(redSquareEdit3, redSquareEdit4);
        QWidget::setTabOrder(redSquareEdit4, spaceBubbleEdit);
        QWidget::setTabOrder(spaceBubbleEdit, spaceBubbleEdit2);
        QWidget::setTabOrder(spaceBubbleEdit2, spaceBubbleEdit3);
        QWidget::setTabOrder(spaceBubbleEdit3, spaceBubbleEdit4);
        QWidget::setTabOrder(spaceBubbleEdit4, towerDefenseEdit);
        QWidget::setTabOrder(towerDefenseEdit, towerDefenseEdit2);
        QWidget::setTabOrder(towerDefenseEdit2, towerDefenseEdit3);
        QWidget::setTabOrder(towerDefenseEdit3, towerDefenseEdit4);
        QWidget::setTabOrder(towerDefenseEdit4, totals);
        QWidget::setTabOrder(totals, totals2);
        QWidget::setTabOrder(totals2, totals3);
        QWidget::setTabOrder(totals3, totals4);
        QWidget::setTabOrder(totals4, addressbookEdit1);
        QWidget::setTabOrder(addressbookEdit1, eventNotificationEdit1);
        QWidget::setTabOrder(eventNotificationEdit1, churchEdit1);
        QWidget::setTabOrder(churchEdit1, totalsDrupalEdit1);

        menuBar->addAction(menuExit->menuAction());
        menuBar->addAction(menuEdit->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuExit->addAction(actionExit);
        menuHelp->addAction(actionDonate);
        menuHelp->addSeparator();
        menuHelp->addAction(actionCheck_for_update);
        menuHelp->addSeparator();
        menuHelp->addAction(actionAbout);
        menuEdit->addAction(actionRefreshData);
        menuEdit->addAction(actionDataClipboard);
        menuEdit->addSeparator();
        menuEdit->addAction(actionSettings);

        retranslateUi(MainWindow);

        toolBox->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QString());
        actionAbout->setText(QApplication::translate("MainWindow", "About", 0, QApplication::UnicodeUTF8));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0, QApplication::UnicodeUTF8));
        actionDataClipboard->setText(QApplication::translate("MainWindow", "Data to Clipboard", 0, QApplication::UnicodeUTF8));
        actionRefreshData->setText(QApplication::translate("MainWindow", "Refresh Data", 0, QApplication::UnicodeUTF8));
        actionCheck_for_update->setText(QApplication::translate("MainWindow", "Check for update...", 0, QApplication::UnicodeUTF8));
        actionSettings->setText(QApplication::translate("MainWindow", "Settings", 0, QApplication::UnicodeUTF8));
        actionDonate->setText(QApplication::translate("MainWindow", "Donate", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("MainWindow", "PlaatSoft", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Pong2", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "RedSquare", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "BibleQuiz", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "SpaceBubble", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "TowerDefense", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("MainWindow", "KnightsQuest", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Google Code", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "Pong2", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "BibleQuiz", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "RedSquare", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "SpaceBubble", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "TowerDefense", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("MainWindow", "KnightsQuest", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Totals", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindow", "Pong2", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MainWindow", "BibleQuiz", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("MainWindow", "RedSquare", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindow", "SpaceBubble", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindow", "TowerDefense", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("MainWindow", "KnightsQuest", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "Totals", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "CodeMii", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "Pong2", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "BibleQuiz", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "RedSquare", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "SpaceBubble", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "TowerDefense", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("MainWindow", "KnightsQuest", 0, QApplication::UnicodeUTF8));
        toolBox->setItemText(toolBox->indexOf(page), QApplication::translate("MainWindow", "Wii Downloads", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "PlaatSoft", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MainWindow", "Addressbook", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MainWindow", "Event Notification", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MainWindow", "Church Admin", 0, QApplication::UnicodeUTF8));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "Totals", 0, QApplication::UnicodeUTF8));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "Google Code", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("MainWindow", "Addressbook", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindow", "Event Notification", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindow", "Church Admin", 0, QApplication::UnicodeUTF8));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "Totals", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MainWindow", "Addressbook", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("MainWindow", "Event Notification", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindow", "Church Admin", 0, QApplication::UnicodeUTF8));
        toolBox->setItemText(toolBox->indexOf(page_2), QApplication::translate("MainWindow", "Drupal Downloads", 0, QApplication::UnicodeUTF8));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "Totals", 0, QApplication::UnicodeUTF8));
        groupBox_11->setTitle(QApplication::translate("MainWindow", "Google Code", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("MainWindow", "PlaatStats", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("MainWindow", "PlaatScore", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("MainWindow", "RedSquare", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("MainWindow", "KnightsQuest", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("MainWindow", "ChatCostCalc", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("MainWindow", "WarQuestClient", 0, QApplication::UnicodeUTF8));
        groupBox_12->setTitle(QApplication::translate("MainWindow", "PlaatSoft", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("MainWindow", "PlaatStats", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("MainWindow", "RedSquare", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("MainWindow", "PlaatScore", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("MainWindow", "KnightsQuest", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("MainWindow", "ChatCostCalc", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("MainWindow", "WarQuestClient", 0, QApplication::UnicodeUTF8));
        groupBox_13->setTitle(QApplication::translate("MainWindow", "Totals", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("MainWindow", "PlaatStats", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("MainWindow", "PlaatScore", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("MainWindow", "RedSquare", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("MainWindow", "KnightsQuest", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("MainWindow", "ChatCostCalc", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("MainWindow", "WarQuestClient", 0, QApplication::UnicodeUTF8));
        toolBox->setItemText(toolBox->indexOf(page_3), QApplication::translate("MainWindow", "Windows Downloads", 0, QApplication::UnicodeUTF8));
        menuExit->setTitle(QApplication::translate("MainWindow", "File", 0, QApplication::UnicodeUTF8));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", 0, QApplication::UnicodeUTF8));
        menuEdit->setTitle(QApplication::translate("MainWindow", "Actions", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_STATS_H
